### ISSUE TITLE
Cannot make it work on linux

### ISSUE THREAD

**Issue by aik** [spcmnspff99/CycloTrain#1]
Right after flashing to gb580 firmware the device reports:
* 11 waypoints on device
* 730379 trackpoints on device

I erased all of them via [X] and [Z] (took some time) but the device keeps saying the waypoints and trackpoints are there. Windows tool seems to have them cleared but back to linux - points are there. However when I try downloading them in linux, I get:

Download Waypoints
Traceback (most recent call last):
  File "./CycloTrain", line 284, in <module>
    main()
  File "./CycloTrain", line 211, in main
    choose()
  File "./CycloTrain", line 205, in choose
    choose()
  File "./CycloTrain", line 205, in choose
    choose()
  File "./CycloTrain", line 205, in choose
    choose()
  File "./CycloTrain", line 172, in choose
    results = gb.exportWaypoints(waypoints)
  File "/home/aik/timex/CycloTrain/gb580.py", line 706, in exportWaypoints
    rendered = template.render(waypoints = waypoints)
  File "/home/aik/timex/CycloTrain/templates.py", line 510, in render
    exec self.code in context.runtime, context
  File "/home/aik/timex/CycloTrain/waypoint_template.txt", line 7, in <module>
    'title':'$waypoint.title',
  File "/home/aik/timex/CycloTrain/templates.py", line 421, in to_unicode
    return _decode_unicode(value, self.encoding, self.errors)
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfb in position 0: invalid start byte

What is wrong exactly? :)

**Comment by aik** [comment]
btw other than that, it works
